[build]
  command = "yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.5.1" # updated to Node 20
  NPM_FLAGS = "--no-optional"
  YARN_VERSION = "1.22.19"
  YARN_FLAGS = "--no-optional"
  NODE_OPTIONS = "--max_old_space_size=4096"

[dev]
  command = "yarn dev"
  port = 3000
  publish = "dist"
  targetPort = 5173  # Vite default port

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "same-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
